name: VanillaPlus
version: '${project.version}'
api-version: '1.21.8'

bootstrapper: ch.andre601.vanillaplus.bootstrap.VanillaPlusBootstrap
main: ch.andre601.vanillaplus.VanillaPlus

dependencies:
  server:
    ItemsAdder:
      load: BEFORE
      required: false
    WorldGuard:
      load: BEFORE
      required: false
    IAWAILA:
      load: BEFORE
      required: false
    PlaceholderAPI:
      load: BEFORE
      required: false